const FOOD_DATA = [
  {"name":"Leg Hamstring Curls",
    "difficulty":"3/5",
  },
  {"name":"Barbell Back Squat",
    "difficulty":"4/5",
  },
  {"name":"Tuck Planche",
    "difficulty":"4.5/5",
  },
  {"name":"Lateral Lunge",
    "difficulty":"2.5/5",
  },
  {"name":"Pistol Squat",
    "difficulty":"3.5/5",
  },
  {"name":"Strict Pullup",
    "difficulty":"4/5",
  },
  {"name":"Arm Overhead Squat",
    "difficulty":"3.5/5",
  },
  {"name":"Prone walkout",
    "difficulty":"1.5/5",
  },
  {"name":"Handstand push-up",
    "difficulty":"4/5",
  },
  {"name":"Bicycle",
    "difficulty":"2/5",
  },
  {"name":"Forearm plank",
    "difficulty":"2/5",
  },
  {"name":"Bicycle crunch",
    "difficulty":"2.5/5",
  },
  {"name":"Barbell Back Squat",
    "difficulty":"4/5",
  },
  {"name":"Tuck Planche",
    "difficulty":"3.5/5",
  },
  {"name":"Alternate leg push-off",
    "difficulty":"2.5/5",
  },
  {"name":"High T plank rotation",
    "difficulty":"2.5/5",
  },
  {"name":"Bear Crawl Exercise ",
    "difficulty":"2.5/5",
  },
];